apiVersion: v1
kind: Pod
metadata:
  name: webapp2
spec:
  containers:
    - name: signup
      image: amazonlinux
      command: ["/bin/bash", "-c", "while true;do echo signup; done"]
    - name: login
      image: httpd
      ports:
        - containerPort: 80
