apiVersion: v1
kind: Pod
metadata:
  name: flipkart
spec:
  containers:
    - name: signup
      image: centos
      command: ["/bin/bash", "-c", "sleep 1500"]
      volumeMounts:
        - name: prj
          mountPath: "/tmp/signup"
    - name: login
      image: centos
      command: ["/bin/bash", "-c", "sleep 1500"]
      volumeMounts:
        - name: prj
          mountPath: "/tmp/login"
  volumes:
    - name: prj
      emptyDir: {}
