apiVersion: v1
kind: Pod
metadata:
  name: webapp1
  labels:
    batch: archos
    env: dev
spec:
  containers:
    - name: login
      image: ubuntu
      ports:
        - containerPort: 80
