apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: amazon
spec:
  replicas: 3
  selector:
     matchExpressions:
       - {key: myname, operator: In, values: [signup,home,login]}
       - {key: env, operator: NotIn, values: [amazon]}
  template:
    metadata:
      name: devops
      labels:
        myname: signup
    spec:
      containers:
        - name: signup
          image: httpd
          ports:
            - containerPort: 80
